### ISSUE TITLE
Hacktoberfest Eligiblity

### ISSUE THREAD

**Issue by dencim** [CCRCFISAT/Acharya-Python#6]
"Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR."

Above could be done by the maintainer to count pull requests towards hacktoberfest

**Comment by ccrc-fisat** [comment]
It is already done
